name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build image
      run: DOCKER_BUILDKIT=1 docker build --no-cache . --file Dockerfile -t acidrs/ftbskies2:latest |
        docker build --no-cache . --file Dockerfile -t acidrs/ftbskies2:1.5.2
    - name: push image to docker hub
      run: |
        docker login -u acidrs -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push acidrs/ftbskies2:latest
        docker push acidrs/ftbskies2:1.5.2
